[parity]
chain = "fifu-spec0.json"
base_path = "/home/eric/go/src/github.com/Eric-GreenComb/parity-poa/parity0"
[network]
port = 30300
[rpc]
port = 8540
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
[ui]
port = 8180
[websockets]
port = 8450