[parity]
chain = "fifu-spec.json"
base_path = "/home/eric/go/src/github.com/Eric-GreenComb/parity-poa/parity3"
[network]
port = 30303
[rpc]
port = 8543
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
cors = ["*"]
[ui]
port = 8183
[websockets]
port = 8453
[ipc]
disable = true